'use strict';
(()=>{
const D=window.RADAR,$=id=>document.getElementById(id),money=v=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(v)+' ₽',e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const refs=ids=>ids.map(i=>`<a href="#s${i}">[${i}]</a>`).join(' ');
const distance=(a,b)=>{const r=Math.PI/180,dlat=(b.lat-a.lat)*r,dlng=(b.lng-a.lng)*r;return 6371000*2*Math.atan2(Math.sqrt(Math.sin(dlat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dlng/2)**2),Math.sqrt(1-(Math.sin(dlat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dlng/2)**2)));};
const scenario=x=>{const base=x.buys*x.check*x.days,delta=x.buys*(x.target-x.share)/100*x.extra*x.days;return{base,delta,changed:base+delta};};
window.RadarMath={distance,scenario};
sources.push(...D.extraSources);sources[12][2]='7 вручную отобранных отзывов 2023–2026; рейтинг 4,5; 364 оценки, 140 текстовых отзывов. Счётчики динамические, не продажи.';
competitors[6].kind='catalog';competitors[6].price='Капучино 400 мл — 320 ₽ в карточке Яндекс';competitors[6].limit='Дата меню «26 января» без года. Цена не подтверждена как текущая; рейтинг взят из более свежей страницы отзывов.';competitors[6].refs.push(24,25);render();
$('source-list').innerHTML=sources.map((s,i)=>`<li id="s${i+1}"><a href="${e(s[1])}" target="_blank" rel="noopener noreferrer">${e(s[0])}</a><br><span class="muted">Проверено ${D.checked} · ${e(s[2])}</span></li>`).join('');
const themes=['Вкус','Скорость','Цена','Обслуживание','Посадка','Ассортимент','Атмосфера'];
const negative=themes.map(t=>({t,n:D.reviews.filter(r=>r[3].includes(t)).length})).sort((a,b)=>b.n-a.n);
$('radar-kpis').innerHTML=[['7','Исследованных конкурентов','#radar','Отобранные точки центра Уфы'],['355 ₽','Медиана капучино 400 мл','#prices','Только официальная группа, n=1'],['355–355 ₽','Диапазон этой группы','#prices','Не диапазон рынка; n=1'],[String(D.reviews.length),'Разобранных отзывов','#voice','2 точки · 2023–2026 · ручной отбор'],[negative[0].t,'Чаще всего в негативе','#voice',`${negative[0].n} из ${D.reviews.length} примеров, не весь рынок`],['5','Приоритетных гипотез','#actions','Результаты тестов отсутствуют']].map(x=>`<a href="${x[2]}"><strong>${x[0]}</strong>${x[1]}<small>${x[3]}</small></a>`).join('');
// Map: groups are real building coordinates, no invented offsets.
const anchors=[{lat:54.724834,lng:55.944174,ref:21},{lat:54.723710,lng:55.942953,ref:20},{lat:54.724205,lng:55.944917,ref:27}];let selected=0,map,markers,circle,centerMark,contextLayer;
function cafeCard(i){selected=i;const c=competitors[i],m=D.cafes[i];$('map-card').innerHTML=`<span class="tag">ТОЧКА ЗДАНИЯ · НЕ ВХОД</span><h3>${e(c.name)}</h3><p>${e(c.address)}</p><p><b>${e(c.price)}</b></p><p>${e(c.hours)}</p><p>${e(c.offer)}</p><p><b>${m.rating.toFixed(1)}</b> · ${m.ratings} оценок · ${m.reviews} текстовых отзывов ${refs([m.rsource])}</p><p class="radar-scope">Счётчики площадки, не продажи и не размер нашей выборки. ${m.rsource===13||m.rsource===25?'Яндекс Карты':'2ГИС'}.</p><p>${e(c.limit)}</p><p>Проверено ${D.checked} · ${refs([...new Set([...c.refs,m.geo])])}</p>`;document.querySelectorAll('#map-list button').forEach(b=>b.classList.toggle('active',+b.dataset.cafe===i));}
function mapRows(){const anchor=anchors[+$('map-anchor').value],radius=+$('map-radius').value,chain=$('map-chain').value,format=$('map-format').value;return D.cafes.map((c,i)=>({...c,i,d:distance(anchor,c)})).filter(c=>(chain==='all'||c.chain===chain)&&(format==='all'||(format==='breakfast'?D.matrix[c.i][0][0]===1:format==='delivery'?D.matrix[c.i][4][0]===1:c[format]===true))&&c.d<=radius);}
function renderMap(){const a=anchors[+$('map-anchor').value],radius=+$('map-radius').value,rows=mapRows();$('map-count').innerHTML=`<b>${rows.length} из 7 исследованных кофеен</b> внутри ${radius} м при выбранных фильтрах. Центр: ${refs([a.ref])}. По прямой, не пеший маршрут.`;$('map-list').innerHTML=rows.map(c=>`<button type="button" data-cafe="${c.i}" class="${c.i===selected?'active':''}">${e(competitors[c.i].name)} · ${Math.round(c.d)} м</button>`).join('')||'<p>Подтверждённых точек по этим условиям нет. Неизвестные услуги не считаются отсутствующими.</p>';
$('map-list').querySelectorAll('button').forEach(b=>b.onclick=()=>{cafeCard(+b.dataset.cafe);if(map)map.panTo([D.cafes[selected].lat,D.cafes[selected].lng]);});
if(rows.length&&!rows.some(c=>c.i===selected))cafeCard(rows[0].i);if(!rows.length)$('map-card').innerHTML='<h3>Нет подтверждённых точек</h3><p>Измените фильтры. Независимый формат и доставка в этой выборке пока не установлены.</p>';
if(!map)return;markers.clearLayers();const groups=new Map();rows.forEach(c=>{const k=c.lat+','+c.lng;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(c);});for(const group of groups.values()){const c=group[0],marker=L.marker([c.lat,c.lng],{icon:L.divIcon({className:'map-group',html:String(group.length),iconSize:[32,32],iconAnchor:[16,16]}),title:group.map(x=>competitors[x.i].name).join(', ')}).addTo(markers);marker.bindPopup(group.map(x=>`<button type="button" data-popup-cafe="${x.i}">${e(competitors[x.i].name)}</button>`).join('<br>'));marker.on('click',()=>cafeCard(c.i));}
if(circle)circle.remove();circle=L.circle([a.lat,a.lng],{radius,color:'#366e5b',weight:2,fillOpacity:.06}).addTo(map);if(centerMark)centerMark.remove();centerMark=L.marker([a.lat,a.lng],{icon:L.divIcon({className:'map-demo',html:'ДЕМО',iconSize:[60,25],iconAnchor:[30,-20]}),interactive:false}).addTo(map);map.fitBounds(circle.getBounds(),{padding:[12,12]});if($('map-context-toggle').checked){if(!map.hasLayer(contextLayer))contextLayer.addTo(map);}else contextLayer.remove();}
if(window.L){map=L.map('radar-map',{scrollWheelZoom:false}).setView([54.724834,55.944174],16);markers=L.layerGroup().addTo(map);contextLayer=L.layerGroup();map.attributionControl.addAttribution('Данные © <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>');fetch('map-context.json').then(r=>{if(!r.ok)throw Error('map');return r.json();}).then(g=>{L.geoJSON(g,{style:f=>f.properties.kind==='building'?{color:'#c3cdbd',weight:1,fillColor:'#dce2d5',fillOpacity:.65}:{color:'#c6cabc',weight:3,opacity:.8},onEachFeature:(f,l)=>{if(f.properties.name)l.bindTooltip(e(f.properties.name));}}).addTo(map).bringToBack();}).catch(()=>{$('radar-map').insertAdjacentHTML('afterend','<p class="muted">Фоновая геометрия недоступна; точки и радиусы работают.</p>');});D.places.forEach(p=>{const stop=p.type==='Транспорт';L.marker([p.lat,p.lng],{icon:L.divIcon({className:stop?'map-stop':'map-place',iconSize:stop?[9,9]:[13,13]}),title:p.name}).bindPopup(`<b>${e(p.name)}</b><br>${p.type}<br>Не измеренный поток.<br>${refs(p.refs)}${p.url?` · <a href="${e(p.url)}" target="_blank" rel="noopener">OSM-объект</a>`:''}`).addTo(contextLayer);});map.on('popupopen',ev=>ev.popup.getElement().querySelectorAll('[data-popup-cafe]').forEach(b=>b.onclick=()=>cafeCard(+b.dataset.popupCafe)));}else $('radar-map').innerHTML='<p>Карта недоступна; координаты, расстояния и карточки доступны ниже.</p>';
['map-anchor','map-radius','map-chain','map-format','map-context-toggle'].forEach(id=>$(id).onchange=renderMap);cafeCard(0);renderMap();
// Price groups intentionally never combine different provenance/date certainty.
const priceGroups={official:[{i:0,price:355,source:1,volume:400,date:'Дата обновления не указана · официальное городское меню'}],snapshot:[{i:6,price:320,source:24,volume:400,date:'Обновлено 26 января без года · карточка Яндекс'}]};
priceGroups.both=[...priceGroups.official,...priceGroups.snapshot];
function priceProof(p){const m=D.cafes[p.i];$('price-proof').innerHTML=`<b>${e(competitors[p.i].name)} · капучино ${p.volume} мл · ${money(p.price)}</b><p>${e(p.date)}. Обычная опубликованная позиция, акция не отмечена. На кассе не проверено.</p><p>Рейтинг ${m.rating.toFixed(1)}, ${m.reviews} текстовых отзывов: отдельный срез карточки, не продажи. Цена и рейтинг не обязательно одной даты.</p><p>Проверено ${D.checked} · ${refs([p.source,m.rsource])}</p>`;}
function renderPrices(){const rows=priceGroups[$('price-cohort').value],values=rows.map(x=>x.price).sort((a,b)=>a-b),median=values[Math.floor(values.length/2)],demo=+$('demo-price').value,delta=demo-median;const valid=Number.isFinite(demo)&&demo>=0&&demo<=10000;$('price-summary').textContent=$('price-cohort').value==='both'?'Две опубликованные позиции одинакового объёма. Общая медиана и отклонение от неё не считаются: даты обновления недостаточно определены. Выберите отдельную группу для её расчёта.':`В выбранной группе n=${rows.length}: минимум ${money(values[0])}, медиана ${money(median)}, максимум ${money(values.at(-1))}. ${valid?`Демо ${money(demo)}: ${delta>=0?'+':''}${money(delta)} (${(delta/median*100).toFixed(1)}%) от медианы группы.`:'Введите цену демо от 0 до 10 000 ₽.'}`;
$('price-bars').innerHTML=rows.map(p=>`<button type="button" class="price-row" data-price="${p.i}"><span>${e(competitors[p.i].name)}<small class="radar-scope" style="display:block">${p.i===0?'Официальное · без даты':'Карточка · 26 января, год?'}</small></span><span class="price-track"><span class="price-fill" style="width:${p.price/400*100}%"></span></span><b>${p.price} ₽</b></button>`).join('');$('price-bars').querySelectorAll('button').forEach((b,i)=>b.onclick=()=>priceProof(rows[i]));
const w=480,h=280,left=55,right=25,top=25,bottom=45,x=v=>left+(v-250)/150*(w-left-right),y=v=>top+(5.1-v)/1.1*(h-top-bottom);let svg=`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="Цена капучино 400 мл и рейтинг площадки: ${rows.map(p=>competitors[p.i].name+' '+p.price+' рублей, '+D.cafes[p.i].rating).join('; ')}">`;[4,4.5,5].forEach(v=>svg+=`<line class="gridline" x1="${left}" y1="${y(v)}" x2="${w-right}" y2="${y(v)}"/><text x="15" y="${y(v)+4}">${v.toFixed(1)}</text>`);[250,300,350,400].forEach(v=>svg+=`<text text-anchor="middle" x="${x(v)}" y="${h-18}">${v} ₽</text>`);rows.forEach((p,i)=>{const m=D.cafes[p.i],r=Math.sqrt(m.reviews/Math.PI)*2;svg+=`<circle tabindex="0" role="button" data-point="${i}" cx="${x(p.price)}" cy="${y(m.rating)}" r="${r}" aria-label="${e(competitors[p.i].name)}: ${p.price} рублей, рейтинг ${m.rating}, ${m.reviews} отзывов"><title>${e(competitors[p.i].name)} · ${p.price} ₽ · ${m.rating} · ${m.reviews} отзывов</title></circle><text text-anchor="middle" x="${x(p.price)}" y="${y(m.rating)+r+18}">${e(competitors[p.i].name)}</text>`;});$('price-scatter').innerHTML=svg+'</svg>';$('price-scatter').querySelectorAll('circle').forEach(c=>{c.onclick=()=>priceProof(rows[+c.dataset.point]);c.onkeydown=ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();c.onclick();}};});priceProof(rows[0]);}
$('price-cohort').onchange=renderPrices;$('demo-price').oninput=renderPrices;renderPrices();
const state=s=>s===1?'Есть':s===-1?'Не найдено':'Не проверено';$('offer-matrix').innerHTML=`<thead><tr><th scope="col">Точка</th>${D.columns.map(c=>`<th scope="col">${c}</th>`).join('')}</tr></thead><tbody>${D.matrix.map((row,i)=>`<tr><th scope="row">${e(competitors[i].name)}</th>${row.map((c,j)=>`<td><button type="button" data-row="${i}" data-col="${j}" class="${c[0]===1?'yes':c[0]===-1?'no':'unknown'}" aria-label="${e(competitors[i].name)}, ${D.columns[j]}: ${state(c[0])}">${state(c[0])}</button></td>`).join('')}</tr>`).join('')}<tr><th scope="row">Найдено в источниках / 7</th>${D.columns.map((_,j)=>`<td><b>${D.matrix.filter(r=>r[j][0]===1).length} / 7</b></td>`).join('')}</tr></tbody>`;
$('offer-matrix').querySelectorAll('button').forEach(b=>b.onclick=()=>{const i=+b.dataset.row,j=+b.dataset.col,c=D.matrix[i][j];$('offer-proof').innerHTML=`<b>${e(competitors[i].name)} · ${D.columns[j]}: ${state(c[0])}</b><p>${e(c[2])}. «Есть» не гарантирует доступность сейчас; «не найдено» не доказывает отсутствие.</p><p>Проверено ${D.checked} · ${refs([c[1]])}</p>`;$('offer-proof').scrollIntoView({block:'nearest',behavior:'auto'});});
function reviewRows(){return D.reviews.filter(r=>($('review-cafe').value==='all'||r[0]===+$('review-cafe').value)&&($('review-period').value==='all'||($('review-period').value==='early'?r[1]<'2025':r[1].startsWith($('review-period').value))));}
function reviewProof(theme){const rows=reviewRows(),col=$('review-tone').value==='positive'?2:3,matched=rows.filter(r=>r[col].includes(theme));$('review-proof').innerHTML=`<b>${theme}: ${matched.length} из ${rows.length} отзывов выбранной выборки</b>${matched.length?matched.map(r=>`<article class="review-item"><b>${e(competitors[r[0]].name)} · ${r[1].split('-').reverse().join('.')}</b><p>${e(r[4])}</p>${r[5]?`<blockquote>«${e(r[5])}»</blockquote>`:''}<p class="radar-scope">Парафраз и короткий фрагмент личного опыта, не проверенный факт о работе заведения. ${refs([r[6]])} · Проверено ${D.checked}</p></article>`).join(''):'<p>В выбранных примерах упоминаний этого тона нет.</p>'}`;}
function renderReviews(){const rows=reviewRows(),positive=$('review-tone').value==='positive',col=positive?2:3;const counts=themes.map(t=>({t,n:rows.filter(r=>r[col].includes(t)).length})).sort((a,b)=>b.n-a.n);$('review-summary').textContent=`Выбрано ${rows.length} из ${D.reviews.length} обработанных отзывов. Знаменатель долей — ${rows.length}. Ноль означает отсутствие темы в примерах, не отсутствие проблемы.`;$('review-bars').innerHTML=counts.map(x=>`<button type="button" class="review-bar" data-theme="${x.t}"><span>${x.t}</span><span class="review-track"><span class="review-fill ${positive?'positive':''}" style="width:${rows.length?x.n/rows.length*100:0}%"></span></span><b>${x.n} · ${rows.length?Math.round(x.n/rows.length*100):0}%</b></button>`).join('');$('review-bars').querySelectorAll('button').forEach(b=>b.onclick=()=>reviewProof(b.dataset.theme));reviewProof(counts[0].t);}
['review-tone','review-cafe','review-period'].forEach(id=>$(id).onchange=renderReviews);renderReviews();
const inputs=[['buys','Покупок в день',50,0,500,1,'шт.'],['check','Средний чек в базе',300,0,3000,10,'₽'],['share','Базовая доля с доп. позицией',20,0,100,1,'%'],['target','Новая доля с доп. позицией',35,0,100,1,'%'],['extra','Цена дополнительной позиции',180,0,1500,5,'₽'],['days','Рабочих дней в периоде',26,0,31,1,'дней']];
$('scenario-inputs').innerHTML=inputs.map(([id,title,value,min,max,step,unit])=>`<label for="sc-${id}">${title} · ${unit}<input type="number" id="sc-${id}" min="${min}" max="${max}" step="${step}" value="${value}"><input type="range" id="sc-range-${id}" aria-label="${title}" min="${min}" max="${max}" step="${step}" value="${value}"></label>`).join('');
function renderScenario(){const x=Object.fromEntries(inputs.map(([id])=>[id,+$('sc-'+id).value])),result=scenario(x);$('scenario-results').innerHTML=`<div>Базовый сценарий<strong>${money(result.base)}</strong><small>Условная выручка периода</small></div><div>Изменённый сценарий<strong>${money(result.changed)}</strong><small>При введённых допущениях</small></div><div>Изменение<strong>${result.delta>=0?'+':''}${money(result.delta)}</strong><small>Не прибыль и не прогноз</small></div>`;$('scenario-formula').textContent=`${x.buys} × (${x.target}% − ${x.share}%) × ${x.extra} ₽ × ${x.days} = ${money(result.delta)} дополнительной выручки. База: ${x.buys} × ${x.check} ₽ × ${x.days}.`;}inputs.forEach(([id,,value,min,max])=>{const n=$('sc-'+id),r=$('sc-range-'+id);n.oninput=()=>{n.value=Math.max(min,Math.min(max,+n.value||0));r.value=n.value;renderScenario();};r.oninput=()=>{n.value=r.value;renderScenario();};});$('scenario-reset').onclick=()=>{inputs.forEach(([id,,value])=>{$('sc-'+id).value=value;$('sc-range-'+id).value=value;});renderScenario();};renderScenario();
// Qualitative resource tiers, proposed duration and evidence directness are not measured potential.
const meta=[{cost:1,days:14,evidence:1,label:'Малые ресурсы · интервью и ручной пилот',basis:'Адресная инфраструктура + единичный запрос в отзыве'}, {cost:2,days:14,evidence:0,label:'Средние ресурсы · малая партия и учёт списаний',basis:'Меню + конкретный опыт выбора еды'}, {cost:2,days:14,evidence:2,label:'Средние ресурсы · замеры и перестройка выдачи',basis:'Часы конкурентов; потребность ещё не подтверждена'}, {cost:3,days:14,evidence:2,label:'Ресурсы зависят от условий партнёра',basis:'Контакт и площадка; спрос не подтверждён'}, {cost:2,days:30,evidence:1,label:'Средние ресурсы · вознаграждение и учёт когорты',basis:'Сетевые правила + единичное пожелание'}];
function renderDecisions(){const sort=$('decision-sort').value,rows=opportunities.map((o,i)=>({o,i,m:meta[i]}));if(sort!=='priority')rows.sort((a,b)=>(sort==='cost'?a.m.cost-b.m.cost:sort==='time'?a.m.days-b.m.days:a.m.evidence-b.m.evidence)||a.i-b.i);$('opportunities').innerHTML=rows.map(({o,i,m})=>`<details><summary>${e(o.title)}</summary><div><p class="decision-meta">${m.label} · предложенный пилот ${m.days} дней · основание: ${m.basis}. У всех эффект пока не проверен.</p><div class="flow"><div><strong>Наблюдение · опубликованный факт</strong>${e(o.obs)} ${refs(o.refs)}</div><div><strong>Доказательство и граница</strong>${e(o.limit)} Проверено ${D.checked}.</div><div><strong>Действие · рекомендация</strong>${e(o.act)}</div><div><strong>Способ проверки</strong>${e(o.test)}</div><div><strong>Метрика успеха</strong>${e(o.metric)} Порог задаётся после базы и расчёта затрат.</div><div><strong>Ожидаемый эффект · гипотеза</strong>${e(o.effect)}</div></div><p class="note">Остановка: ${e(o.stop)}</p>${i===1?'<a href="#scenario">Посчитать сценарий допродажи →</a>':''}</div></details>`).join('');}$('decision-sort').onchange=renderDecisions;renderDecisions();
})();
